apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-operator
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql-operator
  template:
    metadata:
      labels:
        app: mysql-operator
    spec:
      serviceAccountName: mysql-operator
      containers:
      - name: operator
        image: roflmaoinmysoul/mysql-operator:1.0.0
        imagePullPolicy: IfNotPresent
        # Оператор, вероятно, слушает все namespace. Если нет, можно передать переменную окружения WATCH_NAMESPACE.
        # env:
        # - name: WATCH_NAMESPACE
        #   value: ""   # пустая строка означает все namespace