{{- if .Values.gateway.create }}
apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: {{ include "my-app.fullname" . }}-gateway
  namespace: {{ .Release.Namespace }}
spec:
  gatewayClassName: {{ .Values.gateway.gatewayClassName }}
  listeners:
    - name: http
      protocol: HTTP
      port: {{ .Values.gateway.port }}
      allowedRoutes:
        namespaces:
          from: All
{{- end }}