apiVersion: v1
kind: Pod
metadata:
  name: nginx-distroless
  labels:
    app: nginx-distroless
spec:
  containers:
    - name: nginx
      image: kyos0109/nginx-distroless
      ports:
        - containerPort: 80