[control_plane]
cp1 ansible_host=10.23.23.100 ansible_user=user

[workers]
wk1 ansible_host=10.23.23.101 ansible_user=user
wk2 ansible_host=10.23.23.102 ansible_user=user
wk3 ansible_host=10.23.23.103 ansible_user=user

[k8s_cluster:children]
control_plane
workers