apiVersion: v1
kind: Service
metadata:
  name: nginx-monitored
  namespace: homework
  labels:
    app: nginx-monitored
spec:
  selector:
    app: nginx-monitored
  ports:
  - name: http
    port: 8000
    targetPort: 8000
  - name: metrics
    port: 9113
    targetPort: 9113