apiVersion: v1
clusters:
- cluster:
    insecure-skip-tls-verify: true
    server: https://192.168.146.128:6443
  name: kubernetes
contexts:
- context:
    cluster: kubernetes
    namespace: homework
    user: cd-user
  name: cd-context
current-context: cd-context
kind: Config
preferences: {}
users:
- name: cd-user
  user:
    token: eyJhbGciOiJSUzI1NiIsImtpZCI6InVWd3Z4Z2stTlRyeVZSdld5Zm5PNDJmNUlLMzR2N1JTWDE3Q0NvU0hfQmcifQ.eyJhdWQiOlsiaHR0cHM6Ly9rdWJlcm5ldGVzLmRlZmF1bHQuc3ZjLmNsdXN0ZXIubG9jYWwiXSwiZXhwIjoxNzgxNjMzODY2LCJpYXQiOjE3ODE1NDc0NjYsImlzcyI6Imh0dHBzOi8va3ViZXJuZXRlcy5kZWZhdWx0LnN2Yy5jbHVzdGVyLmxvY2FsIiwianRpIjoiMTMzOGM3NmMtZDVjYS00NzJlLWEwMmUtMzk2NWJmY2ViNDQ1Iiwia3ViZXJuZXRlcy5pbyI6eyJuYW1lc3BhY2UiOiJob21ld29yayIsInNlcnZpY2VhY2NvdW50Ijp7Im5hbWUiOiJjZCIsInVpZCI6IjY0YzI5ZDYxLTg0MzgtNGY2OC1iYWY4LWI5NTRlMDljNDFlZCJ9fSwibmJmIjoxNzgxNTQ3NDY2LCJzdWIiOiJzeXN0ZW06c2VydmljZWFjY291bnQ6aG9tZXdvcms6Y2QifQ.FzFyc0549tCwtQR-YB3hsWWxPEJRj8O6kXaer9yvQjtt5IrzliiCzcF8zbW1PAmVpkI1jJXFHUMhDhYU1qWdAEYXHO8oKJdicYakMNp6nlEA20QAOHSRccWUJLVzuKXtloWr4IrTrelxghK8A4AhupR_MgkMwvO5saxv3Og9ZvQUo2-yozWG6GQ3cz2r6ipPo0tRD9VlTyw5MFE4cf7UjZwK7yGcN_dn_z3m7FyzxXKp8XwPC-RBYF716Rt8KYynRd5oIdAjOee6rt3dgtzaAS_REDr-OMoEFuD9ZK7FJYL4PZTXcIZGv5Nh6DFohECNxtyO2mYPFwFgmo2lkP5GbQ
