- name: Upgrade control plane
  hosts: control_plane
  become: true
  tags: [cp_upgrade]
  roles:
    - role: upgrade
      vars:
        upgrade_component: 'control-plane'

- name: Upgrade worker nodes
  hosts: workers
  become: true
  serial: 1
  tags: [worker_upgrade]
  roles:
    - role: upgrade
      vars:
        upgrade_component: 'worker'