tolerations:
  - key: node-role
    operator: Equal
    value: infra
    effect: NoSchedule

nodeSelector:
  node-role: infra

datasources:
  datasources.yaml:
    apiVersion: 1
    datasources:
      - name: Loki
        type: loki
        access: proxy
        url: http://loki:3100
        isDefault: true

service:
  type: NodePort
  port: 80
  targetPort: 3000
  nodePort: 30080

adminUser: admin
adminPassword: admin
